[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "warn"
ignore = []

[licenses]
unlicensed = "deny"
allow = [
  "MIT",
  "Apache-2.0",
]
deny = []
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8

[bans]
multiple-versions = "deny"
highlight = "all"
allow = []
deny = []
skip = []
skip-tree = [
  { name = "proc-macro2", version = "<1.0" }, # version-check 0.8.1
  { name = "quote", version = "<1.0" }, # version-check 0.8.1
  { name = "syn", version = "<1.0" }, # version-check 0.8.1
  { name = "unicode-xid", version = "<1.0" }, # version-check 0.8.1
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
