---
name: Bench
"on":
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
  schedule:
    - cron: "0 0 * * TUE"
jobs:
  bench:
    name: Bench
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2

      - name: Install Rust toolchain
        uses: artichoke/setup-rust/build-and-test@v1.9.0
        with:
          toolchain: nightly

      - name: Compile
        run: cargo build --verbose

      - name: Compile tests
        run: cargo bench --no-run

      - name: Test
        run: cargo bench
